version: "3.8"

services:
  orthanc:
    build:
      context: ./orthanc
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json
      
    networks:
      - app-network
  
  triton:
    image: nvcr.io/nvidia/tritonserver:23.12-py3
    container_name: triton_server
    ports:
      - "8000:8000"   # HTTP
      - "8001:8001"   # gRPC
      - "8002:8002"   # Metrics
    volumes:
      - triton-models:/models
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: ["tritonserver", "--model-repository=/models"]

  app:
    build: ./apps
    depends_on:
      - triton
      - orthanc
    networks:
      - app-network
    ports:
      - "8003:8000"
    volumes:
      - lidc-data:/app/data/LIDC
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    # 3D Slicer
    # command: ["monailabel", "start_server", "--app", "/app/radiology", 
    #           "--studies", "/app/data/LIDC/", 
    #           "--conf", "models", "segmentation_lidc"]

    # Ohif
    command: ["monailabel", "start_server", 
              "--app", "/app/radiology",
              "--studies", "http://orthanc:8042/dicom-web",
              "--conf", "models", "segmentation_lidc"]
    

volumes:
  triton-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./triton/model_repository

  lidc-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/LIDC

networks:
  app-network:
    driver: bridge
