_target_: src.models.LIDC_module_ds.LIDC_Module_DS
defaults:
  - criterion: ds_loss.yaml
  - net: stunet_ft.yaml
  - scheduler: warmup_cosine_sam.yaml

ds_ce_loss: 
  _target_: monai.losses.DeepSupervisionLoss
  loss:
    _target_: src.models.losses.CE_loss.CELossMonAI
    reduction: mean

ds_dice_loss: 
  _target_: monai.losses.DeepSupervisionLoss
  loss:
    _target_: monai.losses.DiceLoss
    to_onehot_y: False
    sigmoid: True
    softmax: False
    include_background: True

ds_focal_loss:
  _target_: monai.losses.DeepSupervisionLoss
  loss: 
    _target_: monai.losses.FocalLoss
    to_onehot_y: False
    include_background: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  weight_decay: 0.000001

do_ds: True

# scheduler:
#   _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#   _partial_: true
#   T_max: ${trainer.max_epochs}
  
# compile model for faster training with pytorch 2.0
compile: false
num_classes: 2 # including background