_target_: src.models.LIDC_softmax.LIDC_Module_Softmax
defaults:
  - criterion: combine_loss.yaml
  - net: stunet_ft.yaml
  - scheduler: warmup_cosine_sam.yaml

ce_loss: 
  _target_: src.models.losses.monai_losses.CELoss
  reduction: mean

dice_loss: 
  _target_: src.models.losses.monai_losses.DiceLoss
  to_onehot_y: True
  sigmoid: False
  softmax: True
  include_background: False
  squared_pred: False
  smooth_nr: 0.00001
  smooth_dr: 0.00001

focal_loss:
  _target_: monai.losses.FocalLoss
  to_onehot_y: True
  include_background: False

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00002
  weight_decay: 0.000001

do_ds: False
roi_size: [128, 128, 128]
sw_batch_size: 1
infer_overlap: 0.25
  
# compile model for faster training with pytorch 2.0
compile: false
num_classes: 2 # including background