wandb_callback:
  _target_: src.utils.callbacks.wandb_callback_lidc_3d.LIDC_3D_Callback
  data_nodule_dir: ${data.data_nodule_dir}
  data_lung_dir: ${data.data_lung_dir}
  data_clean_dir: ${data.data_clean_dir}
  data_type: ${data.data_type}
  classes_name: ["Lung Nodule"]
  colors: ["#00FF00", "#FFFF1E", "#FF0000"]
  n_images_to_log: ${data.samples} # train
  number_of_logged_samples: ${data.samples} # validation
  roi_size: ${data.image_size}
  image_size_before_resized: ${data.image_size_before_resized}
  num_classes: ${model.num_classes}
  softmax: True # If output is 2 channels
  do_ds: ${model.do_ds}
  coefficient: 8
  case_names:
    [
      "0481",
      "0912",
      "0050",
      "0624",
      "0462",
      "0001",
      "0098",
      "0565",
      "0423",
      "0003",
      "0139",
      "0485",
      "0045",
      "0563",
      "0061",
      "0404",
      "0415",
      "0815",
      "0854",
      "0858",
      "0942",
      "0978",
      "0998",
      "0834"
    ]
  
  