wandb_callback:
  _target_: src.utils.callbacks.wandb_callback_lidc_3d.LIDC_3D_Callback
  data_nodule_dir: ${data.data_nodule_dir}
  data_lung_dir: ${data.data_lung_dir}
  data_clean_dir: ${data.data_clean_dir}
  data_type: ${data.data_type}
  classes_name: ["Lung Nodule"]
  colors: ["#00FF00", "#FFFF1E", "#FF0000"]
  n_images_to_log: 1 # train
  number_of_logged_samples: 1 # validation
  roi_size: ${data.image_size}
  num_classes: 2
  case_names:
    [
      "0450",
      "0493",
      "0360",
      "0050",
      "0061",
      "0074",
      "0624",
      "0462",
      "0099",
      "0098",
    ]
  
  