wandb_callback:
  _target_: src.utils.callbacks.monai_callbacks.monai_callbacks_brats.SwinUNETRCallback
  data_dir: /data/hpc/dqm/data/brats-2021/TrainingData
  classes_name: ["Tumor Core", "Whole Tumore", "Enhancing Tumor"]
  colors: ["#007339", "#FFFF1E", "#FF0000", "#FFFFFF"]
  n_images_to_log: 1
  frame_nums: [55, 70, 85, 100]
  number_of_logged_samples: 2
  roi_size: [128, 128, 128]
  num_classes: 4
  case_names:
    [
      "01282",
      "00059",
      "00076",
      "00077",
      "00099",
      "00113",
      "00114",
      "00124", 
      "00139",
    ]
  
  