_target_: src.models.losses.focal_tversky_3d.AsymmetricUnifiedFocalLoss

to_onehot_y: True
num_classes: ${model.num_classes}
weight: 0.3 # focal / 1 - weight * tver
gamma: 1.25
delta: 0.8 # back ce / fn
softmax: True