_target_: src.models.STU-Net.stunet_ft_model.STUNET_FT_Model

input_channels: 1
num_classes: 1
model_type: "base"
enable_deep_supervision: ${model.do_ds}
pretrained_weights_base: "/home/duong.quang.minh/project/3D-SegClass-Medical/checkpoints/stunet/base_ep4k.model"
pretrained_weights_large: "/home/duong.quang.minh/project/3D-SegClass-Medical/checkpoints/stunet/large_ep4k.model"