_target_: src.models.swin-unetr.SwinUNETR.SwinUNETR

img_size: ${data.image_size}
in_channels: 1 # Brats: 4 ---- BTCV: 1
out_channels: 1 # Brats: 3 ---- BTCV: 14
patch_size: 2
depths: [2, 2, 2, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
qkv_bias: True
mlp_ratio: 4.0
feature_size: 48
norm_name: instance
spatial_dims: 3
drop_rate: 0.0
attn_drop_rate: 0.0
dropout_path_rate: 0.0
normalize: True
use_checkpoint: True # gradient checkpointing for reduced memory usage: 15 Gb
