_target_: src.models.swin-unetr.components.SwinUNETR

img_size: [128, 128, 128]
in_channels: 4
out_channels: 3
patch_size: 2
depths: [2, 2, 2, 2]
num_heads: [3, 6, 12, 24]
window_size: 7
qkv_bias: True
mlp_ratio: 4.0
feature_size: 48
norm_name: instance
spatial_dims: 3
drop_rate: 0.0
attn_drop_rate: 0.0
dropout_path_rate: 0.0
normalize: True
use_checkpoint: False # gradient checkpointing for reduced memory usage
