_target_: src.models.unetr.UNETR_Segvol.Pretrained_SegVol_UNETR

img_size: ${data.image_size}
in_channels: 1
out_channels: 1
vit_pretrained_path: "/home/duong.quang.minh/project/3D-SegClass-Medical/checkpoints/segvol/ViT_pretrain.ckpt"