_target_: src.models.unetr_pp.unetr_pp_model.UNETR_PP

# Batch size 1 -> 6.2 Gb

in_channels: 1
out_channels: 2
img_size: ${data.image_size} # 128 -> 43M ---- 256 -> 110 M ---- 512 -> 382M (OOM)
patch_size: [4, 4, 4]
feature_size: 16
hidden_size: 256
num_heads: 4
pos_embed: "perceptron"
norm_name: "instance"
dropout_rate: 0.0
depths: [3, 3, 3, 3]
dims: [32, 64, 128, 256]
do_ds: ${model.do_ds}